name: Build

on: [workflow_dispatch]

jobs:
  Build:
    strategy:
      matrix:
        options:
          - os: ubuntu-latest
            framework: net6.0
            runtime: -x64
            codecov: false
          - os: windows-latest
            framework: net6.0
            runtime: -x64
            codecov: true

    runs-on: ${{matrix.options.os}}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Write env vars
        shell: bash
        run: echo "$CI" > env1.txt

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          path: env1.txt

  Publish:
    needs: [Build]

    runs-on: ubuntu-latest

    steps:
      - name: Write env vars
        shell: bash
        run: echo "$CI" > env2.txt

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          path: env2.txt
